name: docker-multiarch-cicd-worker
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches: [main, 'copilot/*']
    tags: ['v*']

concurrency:
  group: docker-multiarch-cicd-worker-${{ github.ref }}
  cancel-in-progress: false

jobs:
  docker-multiarch:
    uses: ohanalabs-ai/github-platform/.github/workflows/docker-multiarch-cicd.yaml@main
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
      artifact-metadata: write
      pull-requests: write
    with:
      registry: ghcr.io
      platforms: linux/amd64,linux/arm64
      docker-compose-file-name: infra/compose/docker-compose.cicd.yml
      docker-compose-target-service: worker
      push-attestations: 'false'
